---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
# yamllint disable rule:indentation
- patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: all
    spec:
      template:
        spec:
          containers:
            - name: manager
              securityContext:
                seccompProfile:
                  $patch: delete
  # yamllint enable rule:indentation
  target:
    kind: Deployment
    labelSelector: app.kubernetes.io/part-of=flux
resources:
- flux-components.yaml
